### PR TITLE
Prospect form update

### PR DESCRIPTION
**Pull request by rinarexhepi**

### CODE REVIEW

**Review by bitsandtea — CHANGES_REQUESTED** [review]
Here you have removed:
- Email
- Submit button and logic

these should be there see [description again](https://trello.com/c/vcCQn86U/3-get-prospect-form-update)

Also this part of the task is missing:
_After the user clicks Submit now: show him a youtube video in the same box (use any youtube URL, we will replace later)_

**Comment by bitsandtea** [comment]
1. The form is still not showing a video, although email and submit are back.
2. Could you also rebase this with main so there are no conflicts?

Screenshot 2023-04-15 at 18 30 22

**Comment by rinarexhepi** [comment]
The video with the success message now shows when clicking the "Submit now" button, but it has somehow affected the validation since the form can also be submitted with empty fields, so this part needs some debugging. Also, just for now, I added a function to reset the modal to its primary state when the user clicks on the "Get started now" button a second time.

**Comment by rinarexhepi** [comment]
With the latest changes, the success message along with the video show upon signing up. Also the modal is reset when closed, but there is this small issue: 
 - When the user opens the modal a second time, they see a green alert that says: "You have signed up! We will email you soon", in my opinion, this alert is totally unnecessary. Let me know what you think :)

**Pull request merged**
